### ISSUE TITLE
Error trying to create managed stack

### ISSUE THREAD

**Issue by ben-spotnana** [spacelift-io/terraform-starter#31]
Trying to follow the readme and getting stuck with creating the managed stack.  Getting an error that the github application installation is not found even though the application installation must have been working enough to create the other resources.  
![image](https://github.com/spacelift-io/terraform-starter/assets/116597310/94a6745f-8d6b-44ee-aee1-0464d0bdda47)

**Comment by akmal-spacelift** [comment]
I believe that you've already solved this shorty after posting it going by an internal chat thread

```
github_enterprise {
    namespace = "yourNamespaceGoesHere" # The GitHub organization / user the repository belongs to
  }
```

This would be needed on every [stack](https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/stack) (if using github + other examples for bitbucket / gitlab in the link).
If you don’t add the block, we’re assuming that you’re using the Spacelift-managed GitHub app.

**Comment by Apollorion** [comment]
Hi, you can now set `TF_VAR_github_app_namespace={your_github_org_name_or_username}` as an environment variable in spacelift to fix this issue.
